---
# tasks file for wordpress_deploy

  - name: install packages (unified)
    package:
      name:
        - php
        - default-mysql-server
        - apache2
        - php-mysql
      state: latest

  - name: Create download  directory if it does not exist
    file:
      path: "/root/download"
      state: directory
      mode: '0440'

  
  - name: download wordpress
    tags: download
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /root/download/
      mode: 0440

  - name: get last downloaded file name
    shell:
      cmd: cd /root/download && ls -t wordpress* | head -1
    register: wp_tar_file


  - name: Last version is...
    debug: var=wp_tar_file.stdout



  - name: Extract wordpress
    shell:
      cmd: tar xvzf /root/download/{{wp_tar_file.stdout}} -C /var/www/


  - name: get pwd
    shell:
      cmd: pwd
    register: current_pwd

  - name: pwd is...
    debug:
      var: current_pwd

  # - name: WAIT
  #   pause:
  #     minutes: 2


  - name: Copy default virtualhost to site-available
    copy:
      src: ./roles/wordpress_deploy/files/000-default.conf
      dest: "/etc/apache2/sites-available/"
      force: yes
      mode: '0644'


  - name: Copy file with owner and permissions
    copy:
      src: ./roles/wordpress_deploy/files/wordpress_dir.conf
      dest: "/etc/apache2/conf-available/"
      mode: '0644'

  - name: make wordpress_dir.conf enabled
    shell:
      cmd: "a2enconf wordpress_dir.conf"

  - name: Start service httpd, if not started
    service:
      name: apache2
      state: started
